//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.course = new HashSet<course>();
            this.instructor = new HashSet<instructor>();
            this.student = new HashSet<student>();
        }
    
        public string dept_name { get; set; }
        public string building { get; set; }
        public Nullable<decimal> budget { get; set; }
    
        public virtual ICollection<course> course { get; set; }
        public virtual ICollection<instructor> instructor { get; set; }
        public virtual ICollection<student> student { get; set; }
    }
}
