//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<advisor> advisor { get; set; }
        public DbSet<classroom> classroom { get; set; }
        public DbSet<course> course { get; set; }
        public DbSet<department> department { get; set; }
        public DbSet<instructor> instructor { get; set; }
        public DbSet<section> section { get; set; }
        public DbSet<student> student { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<takes> takes { get; set; }
        public DbSet<time_slot> time_slot { get; set; }
        public DbSet<users> users { get; set; }
    }
}
