//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.takes = new HashSet<takes>();
        }
    
        public string ID { get; set; }
        public string name { get; set; }
        public string dept_name { get; set; }
        public Nullable<decimal> tot_cred { get; set; }
    
        public virtual advisor advisor { get; set; }
        public virtual department department { get; set; }
        public virtual ICollection<takes> takes { get; set; }
    }
}
