//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.section = new HashSet<section>();
            this.course1 = new HashSet<course>();
            this.course2 = new HashSet<course>();
        }
    
        public string course_id { get; set; }
        public string title { get; set; }
        public string dept_name { get; set; }
        public Nullable<decimal> credits { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<section> section { get; set; }
        public virtual ICollection<course> course1 { get; set; }
        public virtual ICollection<course> course2 { get; set; }
    }
}
