//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        public section()
        {
            this.takes = new HashSet<takes>();
            this.instructor = new HashSet<instructor>();
        }
    
        public string course_id { get; set; }
        public string sec_id { get; set; }
        public string semester { get; set; }
        public decimal year { get; set; }
        public string building { get; set; }
        public string room_number { get; set; }
        public string time_slot_id { get; set; }
    
        public virtual classroom classroom { get; set; }
        public virtual course course { get; set; }
        public virtual ICollection<takes> takes { get; set; }
        public virtual ICollection<instructor> instructor { get; set; }
    }
}
